apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ecr-pull-through.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecr-pull-through.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ecr-pull-through.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecr-pull-through.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "ecr-pull-through.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "ecr-pull-through.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "ecr-pull-through.fullname" . }}-issuer
  secretName: {{ include "ecr-pull-through.fullname" . }}-tls
