---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: {{ include "ecr-pull-through.fullname" . }}
{{- if .Values.useCertManager}}
  annotations: 
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/{{ include "ecr-pull-through.fullname" . }}
{{- end}}
webhooks:
  - name: pull-through.webhook.dev
    clientConfig:
{{- if not .Values.useCertManager}}
      caBundle: {{ .Values.tls.caBundle | b64enc | quote }}
{{- end}}
      service:
        namespace: kube-system
        name: pull-through-webhook
        path: /mutate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
{{- if not .Values.disableWebhookNamespaceSelector}}
    namespaceSelector: 
      {{- .Values.webhookNamspaceSelector | toYaml | nindent 6 }}
{{- end}}
    sideEffects: None
    admissionReviewVersions: ["v1"]