{{- if not .Values.useCertManager}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "ecr-pull-through.fullname" . }}
  labels:
    {{- include "ecr-pull-through.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.tls.caBundle | b64enc | quote }}
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end}}