package main

import (
	"fmt"
	"testing"
)

func TestGeneratePatch(t *testing.T) {
	tests := []struct {
		name                 string
		registryList         []string
		specKey              string
		containerIndex       int
		awsAccountId         string
		awsRegion            string
		containerImage       string
		podNamespace         string
		podGeneratedName     string
		expectedPatchApplied bool
		expectedPatch        map[string]string
		expectedIsDockerHubOfficialImage bool
		expectedIsDockerHubUserImage bool
	}{
		{
			name:                 "Already patched docker library image",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched docker repository image with tag",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/myrepo/myimage:15",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched quay.io image",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/quay.io/myrepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched quay.io image with tag",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/quay.io/myrepo/myimage:34",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched ghcr.io image",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/ghcr.io/myrepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched ghcr.io image with tag",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/quay.io/myrepo/myimage:latest",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched registry.k8s.io image",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "initContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/registry.k8s.io/myrepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Already patched registry.k8s.io image with tag",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "ephemeralContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "1234567890123.dkr.ecr.us-west-2.amazonaws.com/quay.io/myrepo/myimage:foo-bar-baz",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch docker.io library image with docker.io prefix in image name. [containers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage",
			},
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch docker.io library image with docker.io prefix in image name and tag. [initContainers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "initContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/myimage:i-want-a-pony-0.5.1",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/initContainers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage:i-want-a-pony-0.5.1",
			},
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch docker.io library image with docker.io prefix in image name and tag. [ephemeralContainers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "ephemeralContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/myimage:i-want-a-pony-0.5.1",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/ephemeralContainers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage:i-want-a-pony-0.5.1",
			},
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch non-library docker.io image with docker.io prefix in image name. [containers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/foo/bar",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/foo/bar",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "Patch non-library docker.io image with docker.io prefix and tag image name. [initContainers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "initContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/foo/bar:baz-1.2.3",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/initContainers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/foo/bar:baz-1.2.3",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "Patch non-library docker.io image with docker.io prefix and tag in image name. [ephemeralContainers]",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "ephemeralContainers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/foo/bar:baz-1.2.3",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/ephemeralContainers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/foo/bar:baz-1.2.3",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "Patch docker.io library image without registry prefix",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage",
			},
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch a tagged docker.io library image without registry prefix",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myimage:latest",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/library/myimage:latest",
			},
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch non-library docker.io image without registry prefix",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/myRepo/myimage",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "Patch a tagged non-library docker.io image without registry prefix",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myRepo/myimage:latest",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/docker.io/myRepo/myimage:latest",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to docker.io library image without registry prefix",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to a tagged docker.io library image without registry prefix",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myimage:latest",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to non-library docker.io image without registry prefix",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to a tagged non-library docker.io image without registry prefix",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "myRepo/myimage:latest",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to a docker.io library image with docker.io prefix in the image name",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: true,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "When docker.io registry is not configured, do nothing to a docker.io non-library image with docker.io prefix in the image name",
			registryList:         []string{"quay.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "docker.io/myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     true,
		},
		{
			name:                 "When quay.io registry is not configured, do nothing to the image with quay.io prefix in the image name",
			registryList:         []string{"docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "quay.io/myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "When ghcr.io registry is not configured, do nothing to the image with ghcr.io prefix in the image name",
			registryList:         []string{"docker.io", "quay.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "ghcr.io/myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "When registry.k8s.io registry is not configured, do nothing to the image with registry.k8s.io prefix in the image name",
			registryList:         []string{"docker.io", "ghcr.io", "quay.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "registry.k8s.io/myRepo/myimage",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Webhook does not modify ECR library image with ECR Prefix in the image name.",
			registryList:         []string{"docker.io", "ghcr.io", "quay.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.19.2-eksbuild.1",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: false,
			expectedPatch:        nil,
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
		{
			name:                 "Patch a tagged registry.k8s.io library image with registry prefix",
			registryList:         []string{"quay.io", "docker.io", "ghcr.io", "registry.k8s.io"},
			specKey:              "containers",
			containerIndex:       0,
			awsAccountId:         "1234567890123",
			awsRegion:            "us-west-2",
			containerImage:       "registry.k8s.io/kube-apiserver:v1.30.2",
			podNamespace:         "default",
			podGeneratedName:     "mypod-389fw48",
			expectedPatchApplied: true,
			expectedPatch: map[string]string{
				"op":    "replace",
				"path":  "/spec/containers/0/image",
				"value": "1234567890123.dkr.ecr.us-west-2.amazonaws.com/registry.k8s.io/kube-apiserver:v1.30.2",
			},
			expectedIsDockerHubOfficialImage: false,
			expectedIsDockerHubUserImage:     false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			patchApplied, patch := generatePatch(tt.registryList, tt.specKey, tt.containerIndex, tt.awsAccountId, tt.awsRegion, tt.containerImage, tt.podNamespace, tt.podGeneratedName)
			if patchApplied != tt.expectedPatchApplied {
				t.Errorf("expected patchApplied to be %v, got %v", tt.expectedPatchApplied, patchApplied)
			}
			if patchApplied && !equal(patch, tt.expectedPatch) {
				t.Errorf("expected patch to be %v, got %v", tt.expectedPatch, patch)
			}
		})
		t.Run(fmt.Sprintf("isDockerHubOfficialImage - %s", tt.name), func(t *testing.T) {
			actual := isDockerHubOfficialImage(tt.containerImage)
			if actual != tt.expectedIsDockerHubOfficialImage {
				t.Errorf("expected isDockerHubOfficialImage to be %v, got %v", tt.expectedIsDockerHubOfficialImage, actual)
			}
		})
		t.Run(fmt.Sprintf("isDockerHubUserImage - %s", tt.name), func(t *testing.T) {
			actual := isDockerHubUserImage(tt.containerImage)
			if actual != tt.expectedIsDockerHubUserImage {
				t.Errorf("expected isDockerHubUserImage to be %v, got %v", tt.expectedIsDockerHubUserImage, actual)
			}
		})
	}
}

func equal(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}
