name: Auto.Tag

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/autotag-workflow.yaml
      - .github/workflows/slsa-container-generator.yaml
      - cmd/**
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  tag:
    runs-on: ubuntu-latest
    steps: 
    - uses: phish108/autotag-action@v1.1.55
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}