name: CI Workflow

on:
    workflow_dispatch:
    pull_request:
        paths:
        - .github/workflows/ci-workflow.yaml
        - cmd/**
        - Dockerfile
        - go.mod
        - go.sum

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5

        - name: Run Go tests
          run: |
            cd cmd
            go test ./...
    build:
        needs: test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Cache Docker layers
          uses: actions/cache@v4
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-buildx-

        - name: Build Docker image
          run: docker build -t $(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):latest .
