name: package-helm-chart

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-chart-publisher.yaml
      - 'chart/**'
  
  workflow_dispatch:

env:
  CHART_NAME: ecr-pull-through
jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./chart/${{ env.CHART_NAME }}/Chart.yaml)" >> "$GITHUB_OUTPUT"          

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.REPOSITORY }}
          echo ${{ steps.set-variables.outputs.VERSION }}          

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push helm chart
        run: |
          helm package ./chart/${{ env.CHART_NAME }} --version ${{ steps.set-variables.outputs.VERSION }}
          helm push ${{ github.workspace }}/${{ env.CHART_NAME }}-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts

  notify:
    needs: [package-helm-chart]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./chart/${{ env.CHART_NAME }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: op://Home_Lab/Discord-Webhooks/github-actions-bot
      - name: Discord notification
        uses: "Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554"
        with:
          args: |
            {{ EVENT_PAYLOAD.repository.full_name }} has published Release: ${{github.ref_name}}
            Helm Chart: `oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts/${{ env.CHART_NAME }}`
            Version: `${{ steps.set-variables.outputs.VERSION }}`
